// ============================================================
//  Rajendra Showroom – Default Data
// ============================================================

let CATEGORIES = [
  { id: "all",          label: "All Products",   icon: "◈" },
  { id: "Dinner Sets",  label: "Dinner Sets",    icon: "🍽" },
  { id: "Tea Sets",     label: "Tea Sets",       icon: "🫖" },
  { id: "Cups & Mugs",  label: "Cups & Mugs",    icon: "☕" },
  { id: "Plates",       label: "Plates",         icon: "🍽️" },
  { id: "Bowls",        label: "Bowls",          icon: "🥣" },
  { id: "Glassware",    label: "Glassware",      icon: "🥂" },
  { id: "Serving",      label: "Serving",        icon: "🍲" },
  { id: "Cookware",     label: "Cookware",       icon: "🍳" },
  { id: "Cutlery",      label: "Cutlery",        icon: "🍴" },
  { id: "Gift Sets",    label: "Gift Sets",      icon: "🎁" },
];

const DEFAULT_PRODUCTS = [
  {
    id: 1,
    name: "Royal Dinner Set",
    category: "Dinner Sets",
    price: 4999,
    originalPrice: 6999,
    description: "Elegant 12-piece bone china dinner set with gold rim finishing. Perfect for special occasions and everyday luxury dining.",
    image: null,
    inStock: true,
    featured: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 2,
    name: "Classic Tea Set",
    category: "Tea Sets",
    price: 1899,
    originalPrice: 2499,
    description: "6-piece porcelain tea set with teapot, cups and saucers. Traditional craftsmanship with a modern silhouette.",
    image: null,
    inStock: true,
    featured: true,
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 3,
    name: "Stoneware Soup Bowls",
    category: "Bowls",
    price: 1299,
    originalPrice: 1699,
    description: "Set of 6 premium stoneware soup bowls with speckled texture finish. Microwave and dishwasher safe.",
    image: null,
    inStock: true,
    featured: false,
    rating: 4.5,
    reviews: 67,
  },
  {
    id: 4,
    name: "Crystal Wine Glasses",
    category: "Glassware",
    price: 2499,
    originalPrice: 3199,
    description: "Set of 6 lead-free crystal wine glasses. Perfect clarity with an elegant stem — ideal for entertaining.",
    image: null,
    inStock: true,
    featured: true,
    rating: 4.9,
    reviews: 210,
  },
  {
    id: 5,
    name: "Marble Serving Platter",
    category: "Serving",
    price: 1599,
    originalPrice: 1999,
    description: "Premium oval marble-finish ceramic serving platter. A statement piece for your dining table.",
    image: null,
    inStock: true,
    featured: false,
    rating: 4.6,
    reviews: 45,
  },
  {
    id: 6,
    name: "Ceramic Coffee Mugs",
    category: "Cups & Mugs",
    price: 899,
    originalPrice: 1199,
    description: "Set of 4 handcrafted ceramic coffee mugs in warm matte finish. Each piece is unique — made by artisans.",
    image: null,
    inStock: true,
    featured: false,
    rating: 4.7,
    reviews: 158,
  },
  {
    id: 7,
    name: "Gold Rim Dinner Plates",
    category: "Plates",
    price: 2199,
    originalPrice: 2799,
    description: "Set of 6 fine porcelain dinner plates with hand-applied 24K gold rim detail. Timeless elegance.",
    image: null,
    inStock: true,
    featured: true,
    rating: 4.8,
    reviews: 93,
  },
  {
    id: 8,
    name: "Artisan Salad Bowls",
    category: "Bowls",
    price: 1199,
    originalPrice: 1599,
    description: "Set of 4 handcrafted stoneware salad bowls with organic glaze. Perfect for fresh salads and snacks.",
    image: null,
    inStock: true,
    featured: false,
    rating: 4.4,
    reviews: 52,
  },
  {
    id: 9,
    name: "Ceramic Cookware Set",
    category: "Cookware",
    price: 3499,
    originalPrice: 4999,
    description: "3-piece ceramic non-stick cookware set. Toxin-free coating, even heat distribution, elegant design.",
    image: null,
    inStock: true,
    featured: false,
    rating: 4.6,
    reviews: 77,
  },
  {
    id: 10,
    name: "Luxury Cutlery Set",
    category: "Cutlery",
    price: 2999,
    originalPrice: 3999,
    description: "24-piece premium stainless steel cutlery set with brushed gold finish. A complete set for 6 people.",
    image: null,
    inStock: true,
    featured: false,
    rating: 4.9,
    reviews: 134,
  },
];
